# Generated by Django 4.1.3 on 2023-06-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('admin', 'admin'), ('agent', 'agent')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
