# Generated by Django 4.1.3 on 2023-06-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_access_level_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('agent', 'agent')], default='user', max_length=50),
        ),
    ]
