# Generated by Django 4.1.3 on 2023-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('agent', 'agent'), ('admin', 'admin')], default='user', max_length=50),
        ),
    ]
